---
version: 0
os: linux
files:
  - source: .
    destination: /var/www/html
permissions:
  - object: /var/www/html/
    owner: apache
    group: apache
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/httpd_install.sh
      timeout: 300
      runas: root
    - location: scripts/httpd_start.sh
      timeout: 300
      runs: root
